<a href="https://colab.research.google.com/github/ryanrtrindade/Previsao_Tempo/blob/C%C3%B3digos/Tempo_dados_nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/python/weatherAUS.csv')

In [20]:
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [21]:
df.dtypes

Date              object
Location          object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RainTomorrow      object
dtype: object

In [22]:
df_nulos = df.groupby('Location').apply(lambda x: x.isnull().sum())

/tmp/ipykernel_13667/1295545549.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_nulos = df.groupby('Location').apply(lambda x: x.isnull().sum())

In [23]:
df_nulos

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Location,,,,,,,,,,,,,,,,,,,,,
Adelaide,0,0,2,3,102,1489,1424,26,26,274,...,5,5,8,7,3193,3193,5,4,102,103
Albany,0,0,63,54,24,290,520,3040,3040,247,...,49,716,25,25,38,711,39,712,24,24
Albury,0,0,11,11,29,3040,3040,32,32,525,...,9,8,5,8,1751,1613,9,8,29,29
AliceSprings,0,0,1,2,8,215,520,51,51,230,...,3,5,1,3,334,361,0,2,8,9
BadgerysCreek,0,0,36,29,81,3009,3009,76,76,435,...,54,55,168,173,3009,3009,41,44,81,81
Ballarat,0,0,1,1,12,3040,3040,31,31,91,...,21,7,24,26,546,1048,12,6,12,12
Bendigo,0,0,2,5,6,1855,3040,41,40,244,...,7,2,15,10,968,772,3,2,6,6
Brisbane,0,0,9,14,32,19,49,41,41,70,...,4,15,1,8,1,2,4,15,32,32
Cairns,0,0,1,0,52,370,476,19,18,43,...,1,0,1,0,207,230,1,0,52,52
Canberra,0,0,6,3,18,1604,1915,339,337,541,...,63,12,226,221,1072,1263,18,7,18,18
Cobar,0,0,6,3,21,343,2459,42,42,27,...,125,125,30,26,380,308,8,7,21,21
CoffsHarbour,0,0,15,19,56,1224,1515,359,359,347,...,19,22,311,312,813,778,15,14,56,56
Dartmoor,0,0,69,63,67,409,443,69,69,568,...,228,225,64,65,3009,3009,65,64,67,66
Darwin,0,0,1,1,0,54,4,46,42,28,...,1,2,1,2,1,3,0,2,0,1
GoldCoast,0,0,3,7,60,3040,3040,120,120,65,...,14,12,1,1,3040,3040,1,1,60,60
Hobart,0,0,0,1,5,7,14,23,23,41,...,10,13,1,1,1163,1168,1,2,5,5
Katherine,0,0,49,40,18,93,1578,29,29,40,...,81,836,1,5,41,724,42,724,18,19
Launceston,0,0,6,6,12,2899,3040,34,33,460,...,6,10,1153,1153,2315,2298,6,10,12,12
Melbourne,0,0,480,481,758,3,1,14,14,50,...,482,487,480,483,1034,1106,481,484,758,758
MelbourneAirport,0,0,0,0,0,3,1,15,15,40,...,8,9,0,0,0,1,0,0,0,0
Mildura,0,0,0,0,2,117,133,5,5,92,...,3,4,4,2,84,148,1,1,2,2
Moree,0,0,2,0,155,717,954,78,77,108,...,4,5,0,1,538,404,0,0,155,155
MountGambier,0,0,2,5,9,410,443,53,52,84,...,12,10,2,5,110,110,2,5,9,10
MountGinini,0,0,91,53,133,3040,3040,319,319,250,...,436,311,3040,3040,3040,3040,419,295,133,133
Newcastle,0,0,346,235,84,3039,3039,3039,3039,1421,...,239,938,3039,3039,241,933,234,932,84,84
Nhil,0,0,5,6,9,1578,1578,11,11,50,...,5,5,5,5,1578,1578,5,5,9,9
NorahHead,0,0,30,30,75,3004,3004,54,54,107,...,40,32,34,26,3004,3004,40,31,75,75
NorfolkIsland,0,0,1,1,45,234,439,45,44,31,...,5,2,8,2,66,61,5,2,45,45
Nuriootpa,0,0,11,9,6,122,161,49,34,144,...,10,13,7,8,127,769,5,7,6,7
PearceRAAF,0,0,22,21,247,3009,5,145,145,91,...,20,27,21,28,1043,1128,18,26,247,247
Penrith,0,0,28,25,75,3039,3039,65,65,559,...,96,69,3039,3039,3039,3039,39,20,75,75
Perth,0,0,0,1,0,1,5,5,5,134,...,9,8,1,1,2,4,0,1,0,0
PerthAirport,0,0,0,0,0,1,5,46,46,40,...,0,1,2,1,2,4,0,1,0,0
Portland,0,0,9,1,13,409,443,35,35,70,...,49,13,12,10,412,519,48,12,13,13
Richmond,0,0,20,14,58,1385,3009,57,55,853,...,59,60,29,35,2404,2427,40,42,58,58
Sale,0,0,1,1,9,1175,1191,141,141,82,...,19,15,14,15,358,392,2,1,9,9
SalmonGums,0,0,41,40,46,3001,3001,84,84,99,...,36,36,3001,3001,3001,3001,36,36,46,46
Sydney,0,0,4,2,7,51,16,1038,1038,56,...,15,13,21,19,568,563,5,4,7,7
SydneyAirport,0,0,1,0,4,46,16,51,51,8,...,2,4,8,3,4,0,1,1,4,4
Townsville,0,0,2,1,7,91,423,23,23,123,...,0,0,0,0,174,277,0,0,7,7
Tuggeranong,0,0,1,4,41,3039,3039,42,42,645,...,20,13,15,11,3039,3039,20,13,41,41
Uluru,0,0,35,7,56,1578,1578,54,54,66,...,15,4,10,4,1230,1161,15,4,56,57
WaggaWagga,0,0,0,0,33,138,434,28,28,119,...,3,0,0,0,223,173,0,0,33,33
Walpole,0,0,35,39,187,3006,3006,118,86,286,...,63,60,28,26,3006,3006,28,26,187,187
Watsonia,0,0,7,0,10,3,1,37,37,191,...,14,0,2,0,0,1,14,0,10,10
Williamtown,0,0,2,3,456,1063,1654,136,135,87,...,8,7,12,11,602,649,5,2,456,456
Witchcliffe,0,0,9,6,57,3009,3009,34,33,250,...,240,234,134,134,3009,3009,4,2,57,57
Wollongong,0,0,15,11,58,3040,3040,48,48,125,...,29,30,50,19,1695,1623,29,29,58,57
Woomera,0,0,4,3,18,439,1002,39,39,29,...,13,27,11,14,374,659,1,3,18,19

In [24]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [25]:
df_quantitativas = df.select_dtypes(include=['int64','float64'])
df_quantitativas

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
0,13.4,22.9,0.6,NaN,NaN,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8
1,7.4,25.1,0.0,NaN,NaN,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3
2,12.9,25.7,0.0,NaN,NaN,46.0,19.0,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2
3,9.2,28.0,0.0,NaN,NaN,24.0,11.0,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5
4,17.5,32.3,1.0,NaN,NaN,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2.8,23.4,0.0,NaN,NaN,31.0,13.0,11.0,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4
145456,3.6,25.3,0.0,NaN,NaN,22.0,13.0,9.0,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5
145457,5.4,26.9,0.0,NaN,NaN,37.0,9.0,9.0,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1
145458,7.8,27.0,0.0,NaN,NaN,28.0,13.0,7.0,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0
145459,14.9,NaN,0.0,NaN,NaN,NaN,17.0,17.0,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9

In [26]:
df_qualitativas = df.select_dtypes(include=['object'])
df_qualitativas

,Date,Location,WindGustDir,WindDir9am,WindDir3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,W,W,WNW,No,No
1,2008-12-02,Albury,WNW,NNW,WSW,No,No
2,2008-12-03,Albury,WSW,W,WSW,No,No
3,2008-12-04,Albury,NE,SE,E,No,No
4,2008-12-05,Albury,W,ENE,NW,No,No
...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,E,SE,ENE,No,No
145456,2017-06-22,Uluru,NNW,SE,N,No,No
145457,2017-06-23,Uluru,N,SE,WNW,No,No
145458,2017-06-24,Uluru,SE,SSE,N,No,No
145459,2017-06-25,Uluru,NaN,ESE,ESE,No,NaN

In [27]:
df_qualitativas.isnull().sum()

Date                0
Location            0
WindGustDir     10326
WindDir9am      10566
WindDir3pm       4228
RainToday        3261
RainTomorrow     3267
dtype: int64

In [28]:
df_quantitativas.isnull().sum()

MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustSpeed    10263
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
dtype: int64

In [29]:
df[df_quantitativas.columns] = df[df_quantitativas.columns].fillna(df[df_quantitativas.columns].median())

In [30]:
df.isnull().sum()

Date                 0
Location             0
MinTemp              0
MaxTemp              0
Rainfall             0
Evaporation          0
Sunshine             0
WindGustDir      10326
WindGustSpeed        0
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am         0
WindSpeed3pm         0
Humidity9am          0
Humidity3pm          0
Pressure9am          0
Pressure3pm          0
Cloud9am             0
Cloud3pm             0
Temp9am              0
Temp3pm              0
RainToday         3261
RainTomorrow      3267
dtype: int64

In [31]:
moda_rain_tomorrow = df.RainTomorrow.mode().tolist()
moda_rain_today = df.RainToday.mode().tolist()
moda_wind_gust_dir = df.WindGustDir.mode().tolist()
moda_wind_dir_9am = df.WindDir9am.mode().tolist()
moda_wind_dir_3pm = df.WindDir3pm.mode().tolist()

In [32]:
print(moda_rain_tomorrow)
print(moda_rain_today)
print(moda_wind_gust_dir)
print(moda_wind_dir_9am)
print(moda_wind_dir_3pm)

['No']
['No']
['W']
['N']
['SE']

In [33]:
df[df_qualitativas.columns] = df[df_qualitativas.columns].fillna(df[df_qualitativas.columns].mode().iloc[0])

In [34]:
df.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [35]:
df = df.drop('Date', axis=1)

In [36]:
df.to_csv('dataset__chuva_tratado.csv', index=False)

from google.colab import files
files.download('dataset__chuva_tratado.csv')